function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	--CVPI/Police Generic
	AddTextEntry('RETIN_LIV9','West Bromwich Constabulary')
	AddTextEntry('0xD0A61B6B','San Andreas Pursuit Interceptors')
	AddTextEntry('0xF792CF90','Roll Cage')
	AddTextEntry('0xAF357E34','Roll Cage & Rifle Rack')
	AddTextEntry('0x7CC58E60','State Range Antenna')
	AddTextEntry('0xF58E4969','Widebar Rambar')
	AddTextEntry('0x1224EA34','Slicktop')
	AddTextEntry('NPOL_SLICK2','Slicktop')
	AddTextEntry('0xFECF3A9D','ALPR Cameras(PD)')
	AddTextEntry('NPOL_ALPR2','ALPR Cameras & Aero Package')
	AddTextEntry('0x5A48C963','LSPD City Range')
	AddTextEntry('0x680EE4EF','BCSO County Range')
	AddTextEntry('0x9F06D2E2','SASP State Range')
	AddTextEntry('0x2D6614AF','MDT, Radio & Whelen Siren Controller')
	AddTextEntry('0x27A45995','Dash Radar')
	AddTextEntry('0xEBBF35CB','LSPD Push Bar')
	AddTextEntry('0xD8F39034','BCSO Bullbar')
	AddTextEntry('0x0852EEF2','SASP/Ranger Wrap-Around Bullbar')
	AddTextEntry('0xD39C39E7','Evidence Case')
	AddTextEntry('0x288EE3C7','Fire Extinguisher')
	AddTextEntry('0x1A50474A','Cases & Extinguisher')
	AddTextEntry('0xF5DF543C','Divider')
	AddTextEntry('0xFFAD955D','Divider & Gunrack')
	AddTextEntry('0x7CEDE162','Reading Light')
	AddTextEntry('0xF512A148','Add Rear Seats/Remove K9 Cage')
	AddTextEntry('0x1C7478CB','0')
	AddTextEntry('0x2E4D1C7C','1')
	AddTextEntry('0xB18F2302','2')
	AddTextEntry('0xC06EC0C1','3')
	AddTextEntry('0xD54CEA7D','4')
	AddTextEntry('0xE8038FEA','5')
	AddTextEntry('0xA39B0722','6')
	AddTextEntry('0xB4DA29A0','7')
	AddTextEntry('0xC7BCCF65','8')
	AddTextEntry('0xD956F299','9')
	AddTextEntry('0x2F618B3A','Los Santos Police Department')
	AddTextEntry('0xCD32C6DA','Los Santos Police Department K9')
	AddTextEntry('0xDAC66201','Blaine County Sheriffs Office')
	AddTextEntry('0x28C1FDFB','Blaine County Sheriffs Office K9')
	AddTextEntry('0xF64A190C','San Andreas State Police')
	AddTextEntry('0xB8A21DB5','San Andreas State Police K9')
	AddTextEntry('0xC67AB966','Department of Corrections')
	AddTextEntry('0xD420D4B2','San Andreas Park Rangers')
	AddTextEntry('0xE1D6701D','San Andreas Park Rangers K9')
	AddTextEntry('0x9A8132FD','Unmarked/Decommissioned')
	AddTextEntry('0x8C229640','San Andreas State Police V2')
	AddTextEntry('0x75BC6974','San Andreas State Police K9 V2')
	AddTextEntry('0x6676CAE9','Los Santos Police Department V2')
	AddTextEntry('0x306FDEDC','Los Santos Police Department K9 V2')
	AddTextEntry('NPOL_LIV17','BCSO Ghost (HC Only)')
	AddTextEntry('NPOL_LIV18','LSPD Ghost (HC Only)')
	AddTextEntry('NPOL_LIV_CERB','Cerberus SO')
	AddTextEntry('NPOL_C0_DEP','0 - Patrol')
	AddTextEntry('NPOL_C1_DEP','1 - SCU')
	AddTextEntry('NPOL_C2_DEP','2 - HVTU')
	AddTextEntry('NPOL_C3_DEP','3 - Park Rangers')
	AddTextEntry('NPOL_C4_DEP','4 - S.W.A.T.')
	AddTextEntry('NPOL_C5_DEP','5 - SRU')
	AddTextEntry('NPOL_C6_DEP','6 - BTF')
	AddTextEntry('NPOL_C7_DEP','7')
	AddTextEntry('NPOL_C8_DEP','8')
	AddTextEntry('NPOL_C9_DEP','9')
	AddTextEntry('NPOL_C0_RANK','0 - Cadet')
	AddTextEntry('NPOL_C1_RANK','1 - Solo Cadet')
	AddTextEntry('NPOL_C2_RANK','2 - Officer / Deputy')
	AddTextEntry('NPOL_C3_RANK','3 - Sr Officer / Deputy')
	AddTextEntry('NPOL_C4_RANK','4 - Corporal')
	AddTextEntry('NPOL_C5_RANK','5 - Sergeant')
	AddTextEntry('NPOL_C6_RANK','6 - Lieutenant')
	AddTextEntry('NPOL_C7_RANK','7 - Captain')
	AddTextEntry('NPOL_C8_RANK','8 - Ass. Chief / Undersheriff ')
	AddTextEntry('NPOL_C9_RANK','9 - Chief of Police / Sheriff')
	AddTextEntry('NPOL_TAG_S','Supervisor')
	AddTextEntry('NPOL_TAG_C','Command')
	--Police Flags
	AddTextEntry("FLAG_001", "United States of America")
	AddTextEntry("FLAG_002", "Australia")
	AddTextEntry("FLAG_003", "Brazil")
	AddTextEntry("FLAG_004", "Spain")
	AddTextEntry("FLAG_005", "Canada")
	AddTextEntry("FLAG_006", "United Kingdom")
	AddTextEntry("FLAG_007", "Scotland")
	AddTextEntry("FLAG_008", "Japan")
	AddTextEntry("FLAG_009", "Germany")
	AddTextEntry("FLAG_010", "France")
	AddTextEntry("FLAG_011", "Italy")
	AddTextEntry("FLAG_012", "Switzerland")
	AddTextEntry("FLAG_013", "Jamaica")
	AddTextEntry("FLAG_014", "Colombia")
	AddTextEntry("FLAG_015", "Norway")
	AddTextEntry("FLAG_016", "Russia")
	AddTextEntry("FLAG_017", "South Africa")
	AddTextEntry("FLAG_018", "Mexico")
	AddTextEntry("FLAG_019", "Belgium")
	AddTextEntry("FLAG_020", "Sweden")
	AddTextEntry("FLAG_021", "Argentina")
	AddTextEntry("FLAG_022", "Turkey")
	AddTextEntry("FLAG_023", "Ireland")
	AddTextEntry("FLAG_024", "Wales")
	AddTextEntry("FLAG_025", "England")
	--Police Stickers
	AddTextEntry("STICKER_SAPR", "Park Rangers")
	AddTextEntry("STICKER_K9", "K9")
	AddTextEntry("STICKER_SPONS_1", "NP Cards")
	AddTextEntry("STICKER_202", "A_202")
	AddTextEntry("STICKER_238", "A_238")
	AddTextEntry("STICKER_255", "A_255")
	AddTextEntry("STICKER_331", "A_331")
	AddTextEntry("STICKER_337", "A_337")
	AddTextEntry("STICKER_355", "A_355")
	AddTextEntry("STICKER_397", "A_397")
	AddTextEntry("STICKER_402", "A_402")
	AddTextEntry("STICKER_423", "A_423")
	AddTextEntry("STICKER_455", "A_455")
	AddTextEntry("STICKER_460", "A_460")
	AddTextEntry("STICKER_469", "A_469")
	AddTextEntry("STICKER_485", "A_485")
	AddTextEntry("STICKER_B_215", "B_215")
	AddTextEntry("STICKER_B_270", "B_270")
	AddTextEntry("STICKER_B_319", "B_319")
	AddTextEntry("STICKER_B_385", "B_385")
	AddTextEntry("STICKER_B_431", "B_431")
	AddTextEntry("STICKER_B_447", "B_447")
	AddTextEntry("STICKER_B_451", "B_451")
	AddTextEntry("STICKER_B_484", "B_484")
	AddTextEntry("STICKER_B_490", "B_490")
	AddTextEntry("STICKER_C_300", "C_300")
	AddTextEntry("STICKER_C_304", "C_304")
	AddTextEntry("STICKER_C_338", "C_338")
	AddTextEntry("STICKER_C_365", "C_365")
	AddTextEntry("STICKER_C_382", "C_382")
	AddTextEntry("STICKER_C_492", "C_492")
	--Charger
	AddTextEntry("pdcharger_BBAR_1", "Widebar")
	AddTextEntry("pdcharger_BBAR_2", "Widebar for Hellcat Conversion (SRU Leaders)")
	AddTextEntry("NPOL_CHAR_CONVER", "Hellcat Conversion (SRU Leaders)")
	AddTextEntry("pdcharger_LIV_SASP2", "SASP Snow Leopard HP")
	AddTextEntry("NPOL_SLICK3", "Slicktop")
	AddTextEntry("NPOL_SLICK4", "Performance Package")
	AddTextEntry("pdcharger_SPL0", "SRT Spoiler (Cpt+)")
	AddTextEntry("pdcharger_SPL1", "Hellcat Spoiler (SRU Leaders)")
	--Explorer
	AddTextEntry("pdfpiu_ANT1", "LSPD City Range")
	AddTextEntry("pdfpiu_ANT2", "State & County Range")
	AddTextEntry("pdfpiu_BBAR_1", "Widebar")
end)
